// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202001210943023_[-CreateOrder]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
